### PR TITLE
Update Gradle wrapper

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates Gradle wrapper to `2.14` (plus some whitespace fixes).

### CODE REVIEW

**Comment by stkent** [comment]
[Non-whitespace-only diff](https://github.com/btkelly/gnag/pull/91/files?w=1)

**Comment by stkent** [comment]
👍

**Comment by btkelly** [comment]
Looks good 👍

**Comment by friederbluemle** [comment]
> [Non-whitespace-only diff](https://github.com/btkelly/gnag/pull/91/files?w=1)

That's awesome! Good to know :+1:

**Pull request merged**
