### PR TITLE
Update LICENSE.txt

### PR DESCRIPTION
**Pull request by stkent**
https://github.com/blog/2252-license-now-displayed-on-repository-overview

### CODE REVIEW

**Comment by stkent** [comment]
Ah, I see what's happened here. Willfix.

**Comment by stkent** [comment]
@btkelly good for review now.

**Comment by btkelly** [comment]
Ooo the header file, we should have also included this in your Gandalf PR for the license file.

**Comment by stkent** [comment]
I think that was already using a separate file, no?

**Pull request merged**
