### PR TITLE
Fail on any http error.

### PR DESCRIPTION
**Pull request by amatkivskiy**
Hi, 

This is PR for #142 .

### CODE REVIEW

**Comment by btkelly** [comment]
This PR looks good but I want to test a bit because I wonder if this is too strict in the case where possible network errors occur. I wouldn't want the build to fail completely if one out of 20 comments failed to post, I wonder if logging the failure would be sufficient to show the developer what went wrong without failing the entire build. Like I said though, I will test this solution out and see if I run into frequent `IOException` or something along those lines.

**Comment by amatkivskiy** [comment]
@btkelly yes, you are right regarding failing on comments. Especially considering that no comments will be posted ever in case of wrong github info because it will fail immediately  when fetching PR details (`prSha`).

**Comment by stkent** [comment]
Agreed r.e. not wanting to abort on network exceptions. Also note that the build process will be slowed by the swap to make every comment call synchronous. Should only be noticeable if there are a large number of violations.

**Comment by amatkivskiy** [comment]
@stkent yeah, so I will make commenting and status updating synchronous again.

**Comment by btkelly** [comment]
After thinking about it for a couple days I'm thinking that the only synchronous call should be the one to set the status `postUpdatedGitHubStatusAsync`. This should also be the only call that could fail the build and print out debugging information as to why it may have failed. I figure this will catch any configuration issues without increasing build time by much and with minimal chance of network errors causing the failure. Thoughts on that approach @amatkivskiy or @stkent ?

**Comment by amatkivskiy** [comment]
@btkelly Yeah, you are right regarding `postUpdatedGitHubStatusAsync`.
The only thing that I am worried about is `postUpdatedGitHubStatusAsync` is not the first call to Github API in `gnag` flow. This means that when we come to `postUpdatedGitHubStatusAsync` step we know that Github info is correct otherwise the plugin has a broken state (because probably fetching PR details and PR diff has failed).

I think the best way will be to make [PR Details](https://github.com/btkelly/gnag/blob/master/plugin/src/main/groovy/com/btkelly/gnag/tasks/GnagReportTask.java#L100), [PRDiff](https://github.com/btkelly/gnag/blob/master/plugin/src/main/groovy/com/btkelly/gnag/tasks/GnagReportTask.java#L123) and [postUpdatedGitHubStatusAsync](https://github.com/btkelly/gnag/blob/master/plugin/src/main/groovy/com/btkelly/gnag/tasks/GnagReportTask.java#L110) failure critical.
Or at least 
[PR Details](https://github.com/btkelly/gnag/blob/master/plugin/src/main/groovy/com/btkelly/gnag/tasks/GnagReportTask.java#L100) and [postUpdatedGitHubStatusAsync](https://github.com/btkelly/gnag/blob/master/plugin/src/main/groovy/com/btkelly/gnag/tasks/GnagReportTask.java#L110).

What do you think?

**Comment by amatkivskiy** [comment]
@btkelly Completely agree with you. This first `postUpdatedGitHubStatusAsync` will check correctness of the Github info.
But I noticed that when [this method](https://github.com/btkelly/gnag/blob/master/plugin/src/main/groovy/com/btkelly/gnag/tasks/GnagReportTask.java#L68) is called it won't post status because of the [blank `prSha`](https://github.com/btkelly/gnag/blob/master/plugin/src/main/groovy/com/btkelly/gnag/tasks/GnagReportTask.java#L109).

**Comment by btkelly** [comment]
Ah interesting, I think we may have stumble on a bug. I can fix this with a PR or if you want to update your PR that would work as well. I'm thinking instead of making the `postUpdatedGitHubStatus` synchronous we swap that to the `getPRDetails` because that is the first API call made. Similar to my previous comment this should be the only call to fail the build and again thoughts from you guys?

**Comment by amatkivskiy** [comment]
@btkelly Nice. I will update PR.

**Comment by btkelly** [comment]
This looks great @amatkivskiy, thanks for helping out!

**Pull request merged**
