### PR TITLE
change default path to reports

### PR DESCRIPTION
**Pull request by jsibbold**
test reports are generated under the reports directory, so figured this would make sense for all reports

### CODE REVIEW

**Comment by stkent** [comment]
:+1:

**Comment by jsibbold** [comment]
If this clashes with defaults from those other plugins, just close it out, I just whipped this up quickly more as a suggestion than anything.

**Comment by btkelly** [comment]
Have you tested this? I don't think this will work because it's just changing the paths of where to look for these reports. Until we add support for changing the default locations those paths are where PMD, FindBugs, and Checkstyle place their reports be default.

**Comment by jsibbold** [comment]
I'll test it out today

**Comment by jsibbold** [comment]
yeah looks like that's the case, this would be a nice thing to have

**Pull request closed without merging**
