### PR TITLE
Improve extension APIs for Kotlin users

### LINKED ISSUE #190: Kotlin dsl inconsistency
GnagPluginExtension has isEnabled and setEnabled methods. This allows us to use kotlin properties in the kotlin dsl.

```
gnag{
  isEnabled = true
}
```

ReporterExtension uses isEnabled and enabled. This requires us to use the enabled(bool) method instead of kotlin properties to set the enabled value

```
gnag{
    findbugs {
        enabled(true)
        reporterConfig(project.file("config/findbugs.xml"))
    }
}

### PR DESCRIPTION
**Pull request by stkent**
Fixes #190.

Standardizes reporter enabled boolean accessor methods according to
https://kotlinlang.org/docs/reference/java-interop.html#getters-and-setters
so that they can be interacted with as Kotlin properties.

The old methods have been deprecated and should be removed in the next
major version of Gnag (since their removal will be a breaking API change
for Kotlin-based build scripts).

Groovy-based build scripts should not need to be updated in response to
this change.

Kotlin-based build scripts should not need to be updated in response to
this change.

### CODE REVIEW

**Comment by stkent** [comment]
cc @andrewgiang how does this look?

**Comment by andrewgiang** [comment]
Would be nice to have a non breaking change if possible. Would there be any issue of just deprecating the old method and just adding in the new method for kotlin interop?

**Comment by stkent** [comment]
I like that, then we can remove in whatever the next major version is 👍 Will update!

**Comment by stkent** [comment]
@andrewgiang updated!

**Comment by andrewgiang** [comment]
LGTM

**Pull request merged**
